name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # Prevent compiling heavy ML libs from source (use prebuilt wheels)
          pip install --only-binary=:all: numpy scipy scikit-learn pandas
          pip install -r requirements.txt || true  # fallback if file includes extras

      - name: Run install
        run: make install

      - name: Run linting
        run: make lint

      - name: Run formatting
        run: make format

      - name: Run tests
        run: make test

      - name: Deploy (placeholder)
        run: make deploy
