name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.14
        uses: actions/setup-python@v4
        with:
          python-version: 3.14

      - name: Upgrade pip and key packages
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cython scikit-learn

      - name: Install project dependencies
        run: make install

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Format
        run: make format

      - name: Deploy
        run: make deploy
